/**
 * The answer ladder and the answer cache.
 *
 * These tests exist to prove a cost claim, so they count model calls rather
 * than inspecting behaviour indirectly. A change that quietly starts sending
 * every question to a paid provider should fail here loudly.
 */

import test from 'node:test';
import assert from 'node:assert/strict';

import { Chitraq } from '../src/chitraq.js';
import * as answerCache from '../src/context/answer-cache.js';

/**
 * A stand-in for a paid model that counts how often it is called.
 * @param {{quality?: number, grounded?: boolean}} [opts]
 */
function countingModel(opts = {}) {
  const provider = {
    id: 'expensive-model',
    label: 'Expensive model',
    locality: 'local',
    cost: 'free', // kept free so policy does not block it; we count calls, not cost
    model: 'pretend-large-v1',
    calls: 0,
    capabilities: {
      answer: {
        quality: opts.quality ?? 0.95,
        latencyMs: 1,
        costMicros: 0,
        run: async (task) => {
          provider.calls++;
          return {
            answer: opts.grounded === false ? null : `A generated answer about: ${task.question}`,
            grounded: opts.grounded !== false,
            citations: (task.context ?? []).slice(0, 1).map((c) => c.id),
            uncertainty: 'Generated by a model.',
            method: 'generated',
          };
        },
      },
    },
  };
  return provider;
}

/** A workspace with a clear, directly quotable answer in it. */
async function memoryWithAnswer() {
  const c = new Chitraq({ path: ':memory:' });
  await c.remember({
    title: 'Why we dropped the Redis cache',
    body:
      'We dropped the Redis cache because the hit rate never exceeded twelve percent ' +
      'and it added an operational dependency for no measurable win.',
    kind: 'decision',
    enrich: false,
  });
  return c;
}

// ------------------------------------------------------------- the ladder

test('a question your own notes answer never reaches the model', async () => {
  const c = await memoryWithAnswer();
  const model = countingModel();
  c.addProvider(model);

  const answered = await c.ask('why did we drop the redis cache');

  assert.equal(model.calls, 0, 'the expensive provider was not called at all');
  assert.equal(answered.provider, 'builtin');
  assert.equal(answered.escalated, false);
  assert.match(answered.answer, /hit rate/);
  assert.match(answered.ladder.reason, /no model was needed/);
  c.close();
});

test('a question nothing can answer by quoting does reach the model', async () => {
  const c = await memoryWithAnswer();
  const model = countingModel();
  c.addProvider(model);

  // Related enough to retrieve the note, phrased so no single sentence answers it.
  const answered = await c.ask('compare the redis decision with our other caching choices');

  assert.equal(model.calls, 1);
  assert.equal(answered.escalated, true);
  assert.equal(answered.provider, 'expensive-model');
  c.close();
});

test('a synthesis question always escalates, however well the passages match', async () => {
  const c = await memoryWithAnswer();
  const model = countingModel();
  c.addProvider(model);

  const answered = await c.ask('summarize why we dropped the redis cache');
  assert.equal(answered.escalated, true);
  assert.match(answered.ladder.reason, /synthesis/);
  c.close();
});

test('an empty memory does not call the model to invent an answer', async () => {
  const c = new Chitraq({ path: ':memory:' });
  const model = countingModel();
  c.addProvider(model);

  const answered = await c.ask('what is the capital of Peru');

  assert.equal(model.calls, 0, 'asking a model to fill a gap is how a memory engine starts lying');
  assert.equal(answered.grounded, false);
  assert.match(answered.ladder.reason, /memory holds nothing/);
  c.close();
});

test('the user can force a better answer', async () => {
  const c = await memoryWithAnswer();
  const model = countingModel();
  c.addProvider(model);

  const cheap = await c.ask('why did we drop the redis cache');
  assert.equal(model.calls, 0);
  assert.equal(cheap.ladder.canEscalate, true, 'the interface is told a better answer is available');

  const better = await c.askBetter('why did we drop the redis cache');
  assert.equal(model.calls, 1);
  assert.equal(better.escalated, true);
  c.close();
});

test('escalation can be switched off entirely', async () => {
  const c = await memoryWithAnswer();
  const model = countingModel();
  c.addProvider(model);

  const answered = await c.ask('compare everything about caching decisions', { escalate: 'never' });
  assert.equal(model.calls, 0);
  assert.match(answered.ladder.reason, /switched off/);
  c.close();
});

test('canEscalate is false when there is nothing better to escalate to', async () => {
  const c = await memoryWithAnswer();
  const answered = await c.ask('why did we drop the redis cache');
  assert.equal(answered.ladder.canEscalate, false, 'do not offer what does not exist');
  c.close();
});

test('the ladder still works when the model is broken', async () => {
  const c = await memoryWithAnswer();
  c.addProvider({
    id: 'broken-model',
    label: 'Broken',
    locality: 'local',
    cost: 'free',
    capabilities: {
      answer: { quality: 0.99, latencyMs: 1, run: async () => { throw new Error('exploded'); } },
    },
  });

  const answered = await c.ask('compare the caching decisions we have made');
  assert.equal(answered.escalated, false, 'escalation failed');
  assert.ok(answered.context.items.length > 0, 'but the free answer and context survive');
  c.close();
});

// -------------------------------------------------------------- the cache

test('asking the same question twice calls the model once', async () => {
  const c = await memoryWithAnswer();
  const model = countingModel();
  c.addProvider(model);

  const first = await c.ask('summarize the redis decision');
  const second = await c.ask('summarize the redis decision');

  assert.equal(model.calls, 1, 'the second answer came from cache');
  assert.equal(first.cached, false);
  assert.equal(second.cached, true);
  assert.equal(second.answer, first.answer);
  c.close();
});

test('a rephrased question hits the same cache entry', async () => {
  const c = await memoryWithAnswer();
  const model = countingModel();
  c.addProvider(model);

  await c.ask('summarize the redis decision');
  const rephrased = await c.ask('Summarize the Redis decision!');

  assert.equal(model.calls, 1);
  assert.equal(rephrased.cached, true);
  c.close();
});

test('editing the underlying knowledge invalidates the answer', async () => {
  const c = await memoryWithAnswer();
  const model = countingModel();
  c.addProvider(model);

  await c.ask('summarize the redis decision');
  assert.equal(model.calls, 1);

  const target = (await c.search('redis cache')).results[0];
  await c.correct(target.id, { body: 'We dropped Redis because the hit rate was four percent.' }, 'corrected');

  const after = await c.ask('summarize the redis decision');
  assert.equal(after.cached, false, 'a changed fact must not be answered from a stale cache');
  assert.equal(model.calls, 2);
  c.close();
});

test('capturing relevant new knowledge invalidates the answer', async () => {
  const c = await memoryWithAnswer();
  const model = countingModel();
  c.addProvider(model);

  await c.ask('summarize the redis decision');
  assert.equal(model.calls, 1);

  await c.remember({
    title: 'Redis revisited',
    body: 'We are reconsidering the Redis cache decision for the write path.',
    enrich: false,
  });

  const after = await c.ask('summarize the redis decision');
  assert.equal(after.cached, false, 'new material that would be retrieved changes the key');
  c.close();
});

test('irrelevant new knowledge does not invalidate anything', async () => {
  const c = await memoryWithAnswer();
  const model = countingModel();
  c.addProvider(model);

  await c.ask('summarize the redis decision');
  await c.remember({ title: 'Office plants', body: 'The ficus needs watering weekly.', enrich: false });

  const after = await c.ask('summarize the redis decision');
  assert.equal(after.cached, true, 'unrelated captures must not throw away good answers');
  assert.equal(model.calls, 1);
  c.close();
});

test('the cache can be switched off per call', async () => {
  const c = await memoryWithAnswer();
  const model = countingModel();
  c.addProvider(model);

  await c.ask('summarize the redis decision');
  await c.ask('summarize the redis decision', { cache: false });
  assert.equal(model.calls, 2);
  c.close();
});

test('an expired entry is re-asked', async () => {
  const c = await memoryWithAnswer();
  const model = countingModel();
  c.addProvider(model);

  await c.ask('summarize the redis decision');
  c.db.prepare('UPDATE answer_cache SET created_at = ?').run(
    new Date(Date.now() - 400 * 86400000).toISOString()
  );

  const after = await c.ask('summarize the redis decision');
  assert.equal(after.cached, false);
  c.close();
});

test('the cache reports how many calls it has saved', async () => {
  const c = await memoryWithAnswer();
  c.addProvider(countingModel());

  await c.ask('summarize the redis decision');
  await c.ask('summarize the redis decision');
  await c.ask('summarize the redis decision');

  const stats = c.cacheStats();
  assert.equal(stats.savedCalls, 2);
  assert.ok(stats.hitRate > 0.5);
  c.close();
});

test('clearing the cache is possible and reported', async () => {
  const c = await memoryWithAnswer();
  c.addProvider(countingModel());
  await c.ask('summarize the redis decision');

  const { cleared } = c.clearAnswerCache();
  assert.ok(cleared >= 1);
  assert.equal(c.cacheStats().entries, 0);
  c.close();
});

// ------------------------------------------------------------ the claim

test('over a realistic mix, most questions never reach the model', async () => {
  const c = new Chitraq({ path: ':memory:' });
  const model = countingModel();
  c.addProvider(model);

  await c.remember({ title: 'Why we dropped Redis', body: 'We dropped Redis because the hit rate never exceeded twelve percent.', enrich: false });
  await c.remember({ title: 'Nightly batch runtime', body: 'The nightly reconciliation batch takes forty minutes to complete.', enrich: false });
  await c.remember({ title: 'Pricing per seat', body: 'Standard plan pricing is twenty eight dollars per seat per month.', enrich: false });
  await c.remember({ title: 'Engineering headcount', body: 'The engineering team is fifteen people across three squads.', enrich: false });
  await c.remember({ title: 'Deploy schedule', body: 'Deploys go out on Tuesday afternoons after the smoke tests pass.', enrich: false });

  // The kind of thing people actually ask a memory: mostly lookups.
  const questions = [
    'why did we drop redis',
    'how long does the nightly batch take',
    'what is pricing per seat',
    'what is the engineering headcount',
    'when do deploys go out',
    'why did we drop redis',          // a repeat
    'what is pricing per seat',       // another repeat
    'summarize our infrastructure decisions', // genuine synthesis
  ];

  for (const q of questions) await c.ask(q);

  assert.ok(
    model.calls <= 2,
    `expected at most 2 model calls across ${questions.length} questions, got ${model.calls}`
  );
  c.close();
});

test('the cache key is stable and order-independent', () => {
  const a = answerCache.keyFor({
    question: 'why did we drop redis',
    context: [{ id: 'obj_1', contentHash: 'aaa' }, { id: 'obj_2', contentHash: 'bbb' }],
  });
  const b = answerCache.keyFor({
    question: 'Why did we drop Redis?',
    context: [{ id: 'obj_2', contentHash: 'bbb' }, { id: 'obj_1', contentHash: 'aaa' }],
  });
  assert.equal(a, b, 'retrieval order must not change the key');

  const changed = answerCache.keyFor({
    question: 'why did we drop redis',
    context: [{ id: 'obj_1', contentHash: 'ZZZ' }, { id: 'obj_2', contentHash: 'bbb' }],
  });
  assert.notEqual(a, changed, 'edited content must change the key');
});

test('questions that differ only by negation get different keys', () => {
  const yes = answerCache.keyFor({ question: 'is the migration finished', context: [] });
  const no = answerCache.keyFor({ question: 'is the migration not finished', context: [] });
  assert.notEqual(yes, no);
});

test('a slow provider is offered rather than waited on', async () => {
  const c = await memoryWithAnswer();
  const slow = countingModel();
  // Declares itself fast, behaves slowly — exactly what a 3B model on a CPU
  // does, and the reason the decision uses measured time rather than declared.
  slow.capabilities.answer.latencyMs = 500;
  const inner = slow.capabilities.answer.run;
  slow.capabilities.answer.run = async (task) => {
    await new Promise((r) => setTimeout(r, 120));
    return inner(task);
  };
  c.addProvider(slow);
  c.setPolicy({ autoEscalateMaxMs: 50 });

  // Build enough history for the median to be trusted.
  for (let i = 0; i < 3; i++) {
    await c.ask(`compare the caching options number ${i}`, { cache: false });
  }
  const callsAfterWarmup = slow.calls;

  const answered = await c.ask('compare the caching choices we considered', { cache: false });

  assert.equal(slow.calls, callsAfterWarmup, 'it was not called automatically');
  assert.equal(answered.ladder.heldBackForSpeed, true);
  assert.ok(answered.ladder.estimatedWaitMs >= 100, 'the real wait is measured and reported');
  assert.match(answered.ladder.reason, /takes about/);
  assert.equal(answered.ladder.canEscalate, true, 'but it is still offered');
  c.close();
});

test('asking explicitly overrides the speed guard', async () => {
  const c = await memoryWithAnswer();
  const slow = countingModel();
  const inner = slow.capabilities.answer.run;
  slow.capabilities.answer.run = async (task) => {
    await new Promise((r) => setTimeout(r, 120));
    return inner(task);
  };
  c.addProvider(slow);
  c.setPolicy({ autoEscalateMaxMs: 50 });

  for (let i = 0; i < 3; i++) await c.ask(`compare option ${i}`, { cache: false });
  const before = slow.calls;

  const forced = await c.askBetter('compare the caching choices', { cache: false });
  assert.equal(slow.calls, before + 1, 'waiting is fine when the user chose to');
  assert.equal(forced.escalated, true);
  c.close();
});

test('a fast provider is still escalated to automatically', async () => {
  const c = await memoryWithAnswer();
  const fast = countingModel();
  c.addProvider(fast);
  c.setPolicy({ autoEscalateMaxMs: 8000 });

  const answered = await c.ask('compare the caching choices we considered');
  assert.equal(answered.escalated, true, 'the guard must not disable escalation generally');
  assert.ok(!answered.ladder.heldBackForSpeed);
  c.close();
});
